"""Rebuild data/actuals.csv from FRED (no API key needed).

Uses the public fredgraph CSV endpoint, so it only works when the network
policy allows fred.stlouisfed.org. If it is blocked, the bundled
data/actuals.csv keeps working as-is.

Run from the repo root:  python scripts/refresh_actuals.py [--start 2015]
"""

from __future__ import annotations

import argparse
import io
import urllib.request
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "data" / "actuals.csv"

FRED_CSV = "https://fred.stlouisfed.org/graph/fredgraph.csv?id={series}"

HEADER = """\
# Actual released US economic data (generated by scripts/refresh_actuals.py).
# cpi_yoy_dec  = CPI inflation, Dec year-over-year, %
# unemployment_rate_dec = unemployment rate, December, %
# gdp_annual   = real GDP growth, annual average, %
"""


def fetch(series: str) -> pd.DataFrame:
    with urllib.request.urlopen(FRED_CSV.format(series=series), timeout=30) as resp:
        raw = resp.read().decode()
    df = pd.read_csv(io.StringIO(raw))
    df.columns = ["date", "value"]
    df["date"] = pd.to_datetime(df["date"])
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    return df.dropna()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", type=int, default=2015, help="First year to include.")
    args = parser.parse_args()

    rows = []

    cpi = fetch("CPIAUCSL")  # CPI index, monthly, SA
    cpi["yoy"] = cpi["value"].pct_change(12) * 100
    dec = cpi[cpi["date"].dt.month == 12]
    for _, r in dec.iterrows():
        if r["date"].year >= args.start and pd.notna(r["yoy"]):
            rows.append(("cpi_yoy_dec", r["date"].year, round(r["yoy"], 1)))

    unrate = fetch("UNRATE")  # unemployment rate, monthly
    dec = unrate[unrate["date"].dt.month == 12]
    for _, r in dec.iterrows():
        if r["date"].year >= args.start:
            rows.append(("unemployment_rate_dec", r["date"].year, round(r["value"], 1)))

    gdp = fetch("A191RL1A225NBEA")  # real GDP growth, annual, %
    for _, r in gdp.iterrows():
        if r["date"].year >= args.start:
            rows.append(("gdp_annual", r["date"].year, round(r["value"], 1)))

    df = pd.DataFrame(rows, columns=["indicator", "period", "actual"])
    OUT.write_text(HEADER + df.to_csv(index=False))
    print(f"Wrote {len(df)} actual values to {OUT}")


if __name__ == "__main__":
    main()
